version: '3'
services:
    php:
        build: ./docker
        container_name: php
        working_dir: /application
        expose:
            - '9000'
        volumes:
            - ./app:/application
